CREATE TABLE [Const].[Cities] (
    [ID]   SMALLINT      IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (32) NOT NULL,
    CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);
