// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookClub.WEB.Models;

#nullable disable

namespace OnlineBookClub.WEB.Migrations
{
    [DbContext(typeof(OnlineBookClubContext))]
    [Migration("20240228171234_BugFix_4")]
    partial class BugFix_4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<short?>("EventCount")
                        .HasColumnType("smallint");

                    b.Property<string>("Image")
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<byte>("LevelId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("Id"), 70);

                    b.HasIndex("LevelId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.City", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.Department", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("Id"), 100);

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.District", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<short>("CityId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("Id"), 70);

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.Level", b =>
                {
                    b.Property<byte>("LevelId")
                        .HasColumnType("tinyint");

                    b.Property<short>("ExperiencePoint")
                        .HasColumnType("smallint");

                    b.HasKey("LevelId");

                    b.HasIndex("LevelId");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("LevelId"), 70);

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.Rating", b =>
                {
                    b.Property<byte>("Rate")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Point")
                        .HasColumnType("tinyint");

                    b.HasKey("Rate");

                    b.HasIndex("Rate");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("Rate"), 70);

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.School", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<short>("DistrictId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("Id"), 70);

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.UserAchievement", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("EventId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.UserBookListType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserBookListType");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset?>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CREATED_USER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool?>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool?>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("MODIFIED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MODIFIED_USER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SchoolId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventDetail", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("EventId");

                    b.ToTable("EventDetails");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventParticipant", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("MODIFIED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("RatingRate")
                        .HasColumnType("tinyint");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("RatingRate");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset?>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventRatings");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventRequirement", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<DateTimeOffset>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CREATED_USER_ID")
                        .HasColumnType("int");

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("MODIFIED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MODIFIED_USER_ID")
                        .HasColumnType("int");

                    b.Property<short>("SchoolId")
                        .HasColumnType("smallint");

                    b.Property<byte>("UserRoleId")
                        .HasColumnType("tinyint");

                    b.HasKey("EventId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("EventRequirements");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CREATED_USER_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("MODIFIED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MODIFIED_USER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte?>("RowNumber")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventSubjects");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.User.UserBookList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("UserBookListTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserBookListTypeId");

                    b.ToTable("UserBookLists");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.Identity.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CREATED_USER_ID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool?>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("MODIFIED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MODIFIED_USER_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CREATED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("DepartmentId")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool?>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool?>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<byte?>("LevelId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("MODIFIED_DATE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<short?>("Point")
                        .HasColumnType("smallint");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<short>("SchoolId")
                        .HasColumnType("smallint");

                    b.Property<string>("SchoolNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SchoolId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookClub.WEB.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.Achievement", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.Level", "Level")
                        .WithMany("Achievements")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.District", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.School", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.District", "District")
                        .WithMany("Schools")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.UserAchievement", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookClub.WEB.Models.DB.Event.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.Event", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Event.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("School");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventParticipant", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Event.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingRate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventRating", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Event.Event", "Event")
                        .WithMany("EventRatings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventRequirement", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("School");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.EventSubject", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Event.Event", "Event")
                        .WithMany("EventSubjects")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.User.UserBookList", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.UserBookListType", "UserBookListType")
                        .WithMany()
                        .HasForeignKey("UserBookListTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserBookListType");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.Identity.AppUser", b =>
                {
                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId");

                    b.HasOne("OnlineBookClub.WEB.Models.DB.Const.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Level");

                    b.Navigation("School");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.District", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Const.Level", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("OnlineBookClub.WEB.Models.DB.Event.Event", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("EventRatings");

                    b.Navigation("EventSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
